# Generated by Django 5.2 on 2025-04-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Maize', 'Maize'), ('Barley', 'Barley'), ('Soybean', 'Soybean')], max_length=50)),
                ('soil_type', models.CharField(choices=[('Loamy', 'Loamy'), ('Clay', 'Clay'), ('Sandy', 'Sandy'), ('Peaty', 'Peaty')], max_length=50)),
                ('planting_date', models.DateField()),
                ('spacing', models.FloatField()),
                ('moisture', models.FloatField()),
                ('temperature', models.FloatField()),
                ('sunlight', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('soil_ph', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_stage', models.CharField(choices=[('Seedling', 'Seedling'), ('Vegetative', 'Vegetative'), ('Reproductive', 'Reproductive'), ('Maturity', 'Maturity')], max_length=50)),
                ('predicted_yield', models.FloatField()),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.crop')),
            ],
        ),
    ]
