# Generated by Django 5.2 on 2025-04-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='spacing',
        ),
    ]
